language: android
jdk: oraclejdk7
android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository
# Additional components
    - extra-google-google_play_services
    - addon-google_apis-google-23
# Specify at least one system image,
# if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-23
    - sys-img-x86-android-23
# Create and start emulator
    before_script:
    - echo no | android create avd --force -n test -t android-23 --abi armeabi-v7a
    - emulator -avd test -no-skin -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &

    script: gradle build bikeblocker #(TO DO: CHANGE connectedCheck TO builtProjectname)
